name: abstract_io
description: Abstract IO is designed to simplify and generalize saving data both localy and externaly
version: 0.1.2+5
author: Anders Groeschel
repository: https://github.com/AndersGroeschel/abstract_io
homepage: https://github.com/AndersGroeschel/abstract_io

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


